CLASS zrap110_travel_event_handl_02a DEFINITION
  PUBLIC
  FINAL
  FOR EVENTS OF ZRAP110_R_TRAVELTP_02a
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_travel_event_handl_02a IMPLEMENTATION.
ENDCLASS.
